language: generic
services:
  - docker
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - bash first_install.sh
  - cd laradock
  - docker-compose up --build -d workspace
  - docker-compose ps
  - docker-compose exec workspace bash -c "composer install --prefer-source --no-interaction
    --quiet && php artisan key:generate --ansi && npm install --quiet && npm run dev"
script:
  - docker-compose exec workspace bash -c "mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml"
  - docker-compose exec workspace bash -c "vendor/bin/phpcs --standard=PSR12 ./app/Http"
after_success:
  - travis_retry docker-compose exec workspace bash -c "vendor/bin/php-coveralls"
notifications:
  email: false