# setting language to generic because we dont need php installed (everything is inside docker)
language: generic
services:
  - docker

# don't build submodules automatically
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# install dependencies
install:
  - ./first_install.sh
  - cd laradock
  - docker-compose up --build -d workspace
  - docker-compose ps
  - docker-compose exec workspace bash -c "composer install --prefer-source --no-interaction --quiet && php artisan key:generate --ansi && npm install --quiet && npm run dev"

# run the tests and phpcs
script:
  - docker-compose exec workspace bash -c "vendor/bin/phpunit"
  - docker-compose exec workspace bash -c "vendor/bin/phpcs --standard=PSR12 ./app/Http"
# no emails please
notifications:
  email: false