language: php
php: 7.1
env:
  - PHPCS=1
  - PHPCS=0
  
matrix:
  exclude:
  - php: 7.1
  - env: PHPCS=1 PHPCS=0

install:
  - ./after.sh
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate
jobs:
  include:
    - stage: Test
      script:
        - if [[ $PHPCS != '1' ]]; then vendor/bin/phpunit; fi
        - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=psr2 ./app/Http; fi
    - stage: Deploy
      script: echo "hello";
#      php: 7.1
#      install: skip
#      before_script: skip
#      before_deploy:
#        - composer install --no-dev --optimize-autoloader --no-interaction
#        - php artisan cache:clear
#        - php artisan view:clear
#        - php artisan route:cache
#        - php artisan config:cache
#        - npm install
#        - npm run prod
#        - zip -r latest *
#        - mkdir -p cd_upload
#        - mv latest.zip cd_upload/latest.zip
#      deploy:
#        - provider: s3
#          access_key_id: AKIAJUBHSOK262RJXOZQ
#          secret_access_key: &1
#            secure: TJHZ3im4N7Wt5vwb3wZYb1cOWX22Edw2Lz3bP7gPd6Awmee2Df5BrWWpQYRgUEFjbhD0GhK4ZiGUg4SiTrt7AgebxqHS/NVzgQK1mqK9A0jCHuQwvXEmFqp5mn2ZzGALFAqB06799/niIS/vVW3bWMbF4/z4MT/gL3FsQQZ80dQF9Pu7jKz6D+HRAfrez3v7agZkVT5AexJKdIAeJsYjwBAYWRoGc27IHNYr+1uP3r5XD5UxC5h4PVzHsLY59PTB7cYbJw5acszYloo4PwYvIuM6w3w0AN++e19SmVPfH1FgfHOkKUcez/Np64Hky1z8cCdYiRFSh1XKsiQojTShBC4hzwGBDSysFB8ip7kxKWdNtxC2NHWXxD0IUpJWqxCM1DnuITNRXvp09L23oiAKRenSYP1tnVP563xAIqp4FOhSsuINNmMcqHzK0OpgivVF5ton/EJGMnCQ/0Sqt7+9hzmofqXtXMwytErN9BJ5GmIClLWnPSwb3NEL6L+yDZw/lEnfkroizOjQSWca1Mw208r9ZWwHEAso2qaglwgjjxfkboYx6x1UVqPw0nZji0jHlYcUJMeSEZNVWQkEWrePFDsoWf03bjBKzDuePcWqzm1PXvYgAl+VFzrcKNdkt7aeRNagkxScc7b2B9OToVncei3BM72sewF3pMC2fCxpWW0=
#          local_dir: cd_upload
#          on:
#            branch: master
#          bucket: abrigham.com
#        - provider: codedeploy
#          access_key_id: AKIAJUBHSOK262RJXOZQ
#          secret_access_key: *1
#          bucket: abrigham.com
#          key: latest.zip
#          bundle_type: zip
#          application: abrigham
#          deployment_group: Production
#          on: *2